// Generated by CoffeeScript 1.4.0
(function() {
  var CountdownLatch, mf,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __slice = [].slice;

  mf = require("../../mf");

  CountdownLatch = (function() {

    function CountdownLatch() {
      var args;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      this.step = __bind(this.step, this);

      switch (args.length) {
        case 1:
          this._steps = 1;
          this._onDone = args[0];
          break;
        case 2:
          this._steps = args[0];
          this._onDone = args[1];
          break;
        default:
          throw new Error("Expected either a callback, or a step number and callback");
      }
      if (this._steps < 1) {
        throw new Error("Expected at least one step in CountdownLatch.");
      }
      this._curr = 0;
      this._firing = false;
      this._maybeFire();
    }

    CountdownLatch.prototype.step = function(steps) {
      if (steps == null) {
        steps = 1;
      }
      this._curr += steps;
      return this._maybeFire();
    };

    CountdownLatch.prototype._maybeFire = function() {
      if (this._curr >= this._steps && !this._firing) {
        this._firing = true;
        return mf.core.taskManager().runTaskFast(this._onDone);
      }
    };

    return CountdownLatch;

  })();

  module.exports = CountdownLatch;

}).call(this);
