// Generated by CoffeeScript 1.4.0
(function() {
  var RawConfiguration;

  RawConfiguration = (function() {

    function RawConfiguration(fallback, rawConfig) {
      if (rawConfig == null) {
        rawConfig = {};
      }
      this.rawConfig = rawConfig;
      this.fallback = fallback;
    }

    RawConfiguration.prototype.get = function(key, defaultVal) {
      var _ref, _ref1, _ref2;
      return (_ref = (_ref1 = this.rawConfig[key]) != null ? _ref1 : (_ref2 = this.fallback) != null ? typeof _ref2.get === "function" ? _ref2.get(key, defaultVal) : void 0 : void 0) != null ? _ref : defaultVal;
    };

    return RawConfiguration;

  })();

  module.exports = RawConfiguration;

}).call(this);
